### ISSUE TITLE
[question] Có kế hoạch nâng cấp giao diện không?

### ISSUE THREAD

**Issue by ducconit** [vncore/core#1]
Hiện tại tôi thấy phần giao diện của dự án này khá cổ điển. Tôi muốn hỏi dự án có kế hoạch nâng cấp giao diện không? Hay nếu các dev muốn tùy biến giao diện một cách chi tiết tới từng component thì có được không?

**Comment by vncore** [comment]
> Hiện tại tôi thấy phần giao diện của dự án này khá cổ điển. Tôi muốn hỏi dự án có kế hoạch nâng cấp giao diện không? Hay nếu các dev muốn tùy biến giao diện một cách chi tiết tới từng component thì có được không?

Tất cả các thành phần của vncore để có thể customize.
Với view của admin, sử dụng `php artisan vncore:customize view`, và chỉnh sửa trong `resources/views/vendor/vncore-admin` theo ý mình
